packageExtensions:
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "@nuxtjs/stylelint-module@*":
    dependencies:
      webpack: "*"
  babel-core@*:
    dependencies:
      "@babel/core": "*"
  babel-jest@*:
    dependencies:
      "@babel/core": "*"
  eslint-plugin-vue@*:
    dependencies:
      eslint: "*"
  eslint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      webpack: "*"
  nuxt@*:
    dependencies:
      consola: "*"
  sass-loader@*:
    dependencies:
      webpack: "*"
  stylelint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  ts-loader@*:
    dependencies:
      webpack: "*"
  vue-class-component@*:
    dependencies:
      vue: "*"
  vue-eslint-parser@*:
    dependencies:
      eslint: "*"
  vue-jest@*:
    dependencies:
      "@babel/core": "*"
  vue-property-decorator@*:
    dependencies:
      vue: "*"
  vuetify-loader@*:
    dependencies:
      vue-template-compiler: "*"
      webpack: "*"
  vuetify@*:
    dependencies:
      vue: "*"
  vuex-class@*:
    dependencies:
      vue: "*"
      vuex: "*"
  vuex-module-decorators@*:
    dependencies:
      vue: "*"
      vuex: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
