packageExtensions:
  '@babel/preset-env@*':
    dependencies:
      '@babel/core': '*'
  '@nuxt/components@*':
    dependencies:
      consola: '*'
  '@nuxtjs/eslint-config@*':
    dependencies:
      eslint: '*'
  '@typescript-eslint/eslint-plugin@*':
    dependencies:
      eslint: '*'
  '@typescript-eslint/parser@*':
    dependencies:
      eslint: '*'
  babel-core@*:
    dependencies:
      '@babel/core': '*'
  babel-jest@*:
    dependencies:
      '@babel/core': '*'
  eslint-plugin-vue@*:
    dependencies:
      eslint: '*'
  eslint-webpack-plugin@*:
    dependencies:
      webpack: '*'
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      webpack: '*'
  sass-loader@*:
    dependencies:
      webpack: '*'
  stylelint-webpack-plugin@*:
    dependencies:
      webpack: '*'
  ts-loader@*:
    dependencies:
      webpack: '*'
  vue-class-component@*:
    dependencies:
      vue: '*'
  vue-eslint-parser@*:
    dependencies:
      eslint: '*'
  vue-jest@*:
    dependencies:
      '@babel/core': '*'
  vue-property-decorator@*:
    dependencies:
      vue: '*'
  vuetify@*:
    dependencies:
      vue: '*'
  vuetify-loader@*:
    dependencies:
      vue-template-compiler: '*'
      webpack: '*'
  vuex-class@*:
    dependencies:
      vuex: '*'
      vue: '*'
  vuex-module-decorators@*:
    dependencies:
      vue: '*'
      vuex: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
