packageExtensions:
  '@babel/eslint-parser@*':
    dependencies:
      '@babel/core': '*'
  '@babel/preset-env@*':
    dependencies:
      '@babel/core': '*'
  '@nuxt/babel-preset-app@*':
    dependencies:
      debug: '*'
      supports-color: '*'
  '@nuxt/components@*':
    peerDependenciesMeta:
      vue:
        optional: true
  '@nuxtjs/eslint-config@*':
    peerDependenciesMeta:
      eslint:
        optional: true
  '@nuxtjs/eslint-module@*':
    dependencies:
      eslint: '*'
  '@nuxtjs/vuetify@*':
    peerDependenciesMeta:
      vue:
        optional: false
  '@typescript-eslint/eslint-plugin@*':
    dependencies:
      eslint: '*'
  '@typescript-eslint/parser@*':
    peerDependenciesMeta:
      eslint:
        optional: true
  '@vue/test-utils@*':
    dependencies:
      vue: '*'
  babel-core@*:
    dependencies:
      '@babel/core': '*'
  babel-jest@*:
    dependencies:
      '@babel/core': '*'
  babel-loader@*:
    dependencies:
      '@babel/core': '*'
  cypress@*:
    dependencies:
      typescript: '*'
  eslint-config-prettier@*:
    dependencies:
      eslint: '*'
  eslint-plugin-cypress@*:
    dependencies:
      eslint: '*'
  eslint-plugin-jest@*:
    dependencies:
      eslint: '*'
  eslint-plugin-prettier@*:
    dependencies:
      eslint: '*'
  eslint-webpack-plugin@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      webpack:
        optional: true
    dependencies:
      vue-template-compiler: '*'
  prettier@*:
    peerDependenciesMeta:
      pnpify:
        optional: true
  sass-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  stylelint@*:
    peerDependenciesMeta:
      postcss-syntax:
        optional: false
  stylelint-webpack-plugin@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  ts-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  vue-class-component@*:
    peerDependenciesMeta:
      vue:
        optional: true
  vue-jest@*:
    dependencies:
      '@babel/core': '*'
      vue: '*'
  vue-property-decorator@*:
    peerDependenciesMeta:
      vue:
        optional: true
  vue-router@*:
    peerDependenciesMeta:
      vue:
        optional: true
  vue-template-compiler@*:
    peerDependenciesMeta:
      vue:
        optional: true
  vuetify-loader@*:
    dependencies:
      webpack: '*'
    peerDependenciesMeta:
      vue-template-compiler:
        optional: true
  vuex-class@*:
    dependencies:
      vuex: '*'
    peerDependenciesMeta:
      vue:
        optional: true
  vuex-module-decorators@*:
    peerDependenciesMeta:
      vue:
        optional: true
      vuex:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
