packageExtensions:
  "@vue/vue3-jest@*":
    dependencies:
      "@vue/compiler-sfc": "*"
  eslint-plugin-vue@*:
    dependencies:
      eslint: "*"
  eslint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      webpack: "*"
  sass-loader@*:
    dependencies:
      webpack: "*"
  stylelint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  ts-loader@*:
    dependencies:
      webpack: "*"
  vite-plugin-eslint@*:
    dependencies:
      vite: "*"
  vite-plugin-stylelint@*:
    dependencies:
      vite: "*"
  vue-class-component@*:
    dependencies:
      vue: "*"
  vue-eslint-parser@*:
    dependencies:
      eslint: "*"
  vue-property-decorator@*:
    dependencies:
      vue: "*"
  vuetify-loader@*:
    dependencies:
      vue: "*"
      webpack: "*"
  vuetify@*:
    dependencies:
      vue: "*"
  vuex-class@*:
    dependencies:
      vue: "*"
      vuex: "*"
  vuex-module-decorators@*:
    dependencies:
      vue: "*"
      vuex: "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
