name: End-to-end tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  e2e:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2.4.0

      - name: Print env variables
        run: npx @bahmutov/print-env GITHUB

      - name: Run Cypress 🧪
        uses: cypress-io/github-action@v6
        env:
          CI: 1
          NODE_OPTIONS: "--openssl-legacy-provider"
        with:
          install-command: yarn install
          build: yarn generate
          start: yarn start
          wait-on: "http://localhost:3000"
          command: yarn test:e2e:run --binaries-only

      # Save videos and screenshots as test artifacts
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: cypress/screenshots
          # there might be no screenshots created when:
          # - there are no test failures
          # so only upload screenshots if previous step has failed
          if: failure()
      # video should always be generated
      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
